# Generated by Django 4.1.4 on 2022-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='account_number',
            field=models.IntegerField(default=110, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
