# Generated by Django 4.1.4 on 2022-12-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_loan_name_message_name_alter_users_image_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='sent_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sent_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
